global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'router'

    static_configs:
      - targets: ['debiand843e635fb7.home:9100']
        labels:
          group: 'production'

  - job_name: 'nodes'

    static_configs:
      - targets: ['debian00d861dabdae.home:9100', 'debian00d861c3b883.home:9100']
        labels:
          group: 'production'
